//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyCompany("Adaptive technologies")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Adaptive technologies 2013–2015")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyVersion("2.1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.1.0.0-69fa762")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "Adaptive technologies";
    
    internal const string AssemblyCopyright = "Copyright © Adaptive technologies 2013–2015";
    
    internal const string AssemblyConfiguration = "Debug";
    
    internal const string AssemblyVersion = "2.1.0.0";
    
    internal const string AssemblyFileVersion = "2.1.0.0";
    
    internal const string AssemblyInformationalVersion = "2.1.0.0-69fa762";
    
    private ThisAssembly() {
    }
}
